<script setup>
import { onMounted, ref } from 'vue'
import { showToast } from 'vant'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const route = useRoute(); const router = useRouter(); const authStore = useAuthStore()
const item = ref(null); const images = ref([]); const reviews = ref([]); const reviewSummary = ref({ averageRating: 0, reviewCount: 0 }); const balance = ref(0); const quantity = ref(1); const loading = ref(false); const purchaseVisible = ref(false); const purchasing = ref(false)
async function loadDetail() { loading.value = true; try { const response = await fetch(`/api/shop/items/${route.params.id}`, { headers: { Authorization: `Bearer ${authStore.token}` } }); const result = await response.json(); if (!response.ok || result.code !== 0) throw new Error(result.message || '商品不存在'); item.value = result.data.item; images.value = result.data.images || []; reviews.value = result.data.reviews || []; reviewSummary.value = result.data.reviewSummary || { averageRating: 0, reviewCount: 0 } } catch (error) { showToast(error.message || '详情加载失败') } finally { loading.value = false } }
async function buyNow() { purchaseVisible.value = true; try { const response = await fetch('/api/shop/orders/account', { headers: { Authorization: 'Bearer ' + authStore.token } }); const result = await response.json(); if (response.ok && result.code === 0) balance.value = Number(result.data?.balance || 0) } catch {} }
async function confirmPurchase() { const total = Number(item.value.price || 0) * quantity.value; if (balance.value < total) { showToast('余额不足，请先充值'); return } purchasing.value = true; try { const response = await fetch('/api/shop/orders', { method: 'POST', headers: { Authorization: `Bearer ${authStore.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ itemId: item.value.id, quantity: quantity.value }) }); const result = await response.json(); if (!response.ok || result.code !== 0) throw new Error(result.message || '购买失败'); purchaseVisible.value = false; showToast('购买成功'); router.push(`/shop/orders/${result.data.id}`) } catch (error) { showToast(error.message || '购买失败') } finally { purchasing.value = false } }
onMounted(loadDetail)
</script>

<template>
  <main class="shop-detail-page">
    <van-nav-bar title="详情页" left-arrow @click-left="router.back" />
    <van-loading v-if="loading" class="shop-loading" size="32px" />
    <template v-else-if="item">
      <van-swipe class="detail-gallery" :autoplay="3500" indicator-color="#ff62aa"><van-swipe-item v-for="image in (images.length ? images : [{ imageUrl: item.coverUrl }])" :key="image.id || image.imageUrl"><div class="detail-image" :style="image.imageUrl ? { backgroundImage: `url(${image.imageUrl})` } : {}"><span v-if="!image.imageUrl">♡</span></div></van-swipe-item></van-swipe>
      <section class="detail-info"><div class="detail-price">¥{{ Number(item.price || 0).toFixed(2) }} <small>库存：{{ item.stock }}份</small></div><h1>{{ item.title }}</h1><p>{{ item.description || item.subtitle || '为你认真准备的专属心意。' }}</p><van-divider /><div class="detail-provider"><span class="detail-provider-avatar">♡</span><div><b>提供方：{{ item.sellerName || item.sellerPhone || '恋人小店' }}</b><small>宝贝为你精心准备</small></div></div><van-divider /><div class="detail-quantity"><b>购买数量</b><van-stepper v-model="quantity" min="1" :max="Math.max(item.stock || 1, 1)" /></div></section><section class="detail-reviews"><div class="detail-reviews-head"><h2>商品评价</h2><span>{{ reviewSummary.reviewCount }}条 · {{ Number(reviewSummary.averageRating || 0).toFixed(1) }}分</span></div><div v-if="reviews.length"><article v-for="review in reviews" :key="review.id" class="detail-review"><div class="reviewer-info"><span class="reviewer-avatar"><img v-if="review.reviewerAvatarUrl" :src="review.reviewerAvatarUrl" alt="评价人头像" /><span v-else>{{ (review.reviewerName || '匿').slice(0, 1) }}</span></span><b>{{ review.reviewerName || '匿名用户' }}</b><van-rate :model-value="review.rating" readonly color="#ff62aa" size="14" /></div><p>{{ review.content || '未填写评价内容' }}</p><small>{{ review.createTime }}</small></article></div><van-empty v-else image="search" description="暂无评价" /></section>      <div class="detail-buy-bar"><van-button block round type="primary" color="#ff62aa" @click="buyNow">立即购买</van-button></div>      <div v-if="purchaseVisible" class="purchase-overlay" @click.self="purchaseVisible = false"><div class="purchase-dialog"><h2>确认购买订单</h2><div class="purchase-product"><div class="purchase-thumb" :style="item.coverUrl ? { backgroundImage: `url(${item.coverUrl})` } : {}">♡</div><div><b>{{ item.title }}</b><small>数量：{{ quantity }}</small></div></div><van-divider /><div class="purchase-line"><span>应付总额</span><strong>¥{{ (Number(item.price || 0) * quantity).toFixed(2) }}</strong></div><div class="purchase-line"><span>支付方式</span><b>余额支付（可用：¥{{ balance.toFixed(2) }}）</b></div><div class="purchase-actions"><van-button round plain @click="purchaseVisible = false">取消</van-button><van-button round color="#ff62aa" :loading="purchasing" @click="confirmPurchase">确认购买</van-button></div></div></div>
    </template>
    <van-empty v-else description="商品不存在或已下架" />
  </main>
</template>